# Site settings
title: Reacting to Machine Learning 
url: "https://gfeldman.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "" # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
#timezone: Asia/Chongqing
description: >
  "Notes on building reactive machine learning / data science software."

# Your information
email: gfeldman8@gmail.com
author: "Guy Feldman"
avatar: "//www.gravatar.com/avatar/your_email_md5?d=mm&s=135"
profile: Statistics Ph.D. with an interest in reactive systems.
twitter_username: gfeldman8
github_username:  gfeldman

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

permalink: /archivers/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown
kramdown: 
  syntax_highlighter_opts:
    disable : true

include:
  - data
  - bower-components
  - Illustrations
  
exclude: 
  - package.json
  - node_modules
  - gulpfile.js